baseURL = 'http://beta.prewired.org/'
languageCode = 'en-gb'
title = 'Prewired'

theme = "prewired"

[menu]
  [[menu.main]]
    name = "what we do"
    url = "/what-we-do"
    weight = 1
  [[menu.main]]
    name = "volunteering"
    url = "/volunteer"
    weight = 2
  [[menu.main]]
    name = "resources"
    url = "/resources"
    weight = 3
  [[menu.main]]
    name = "about us"
    url = "/about-us"
    weight = 4

[markup.goldmark.renderer]
unsafe= true